//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.225
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace DigiEncuesta.App.Proxy {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntidadEncuestador", Namespace="http://schemas.datacontract.org/2004/07/DigiEncuesta.Entidades")]
    public partial class EntidadEncuestador : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string NombreField;
        
        private int UsuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((this.UsuarioField.Equals(value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Proxy.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/IniciarSesion", ReplyAction="http://tempuri.org/IService1/IniciarSesionResponse")]
        System.IAsyncResult BeginIniciarSesion(int usuario, string clave, System.AsyncCallback callback, object asyncState);
        
        bool EndIniciarSesion(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/ConsultarUsuario", ReplyAction="http://tempuri.org/IService1/ConsultarUsuarioResponse")]
        System.IAsyncResult BeginConsultarUsuario(int usuario, System.AsyncCallback callback, object asyncState);
        
        DigiEncuesta.App.Proxy.EntidadEncuestador EndConsultarUsuario(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : DigiEncuesta.App.Proxy.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IniciarSesionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public IniciarSesionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ConsultarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public DigiEncuesta.App.Proxy.EntidadEncuestador Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((DigiEncuesta.App.Proxy.EntidadEncuestador)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<DigiEncuesta.App.Proxy.IService1>, DigiEncuesta.App.Proxy.IService1 {
        
        private BeginOperationDelegate onBeginIniciarSesionDelegate;
        
        private EndOperationDelegate onEndIniciarSesionDelegate;
        
        private System.Threading.SendOrPostCallback onIniciarSesionCompletedDelegate;
        
        private BeginOperationDelegate onBeginConsultarUsuarioDelegate;
        
        private EndOperationDelegate onEndConsultarUsuarioDelegate;
        
        private System.Threading.SendOrPostCallback onConsultarUsuarioCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<IniciarSesionCompletedEventArgs> IniciarSesionCompleted;
        
        public event System.EventHandler<ConsultarUsuarioCompletedEventArgs> ConsultarUsuarioCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult DigiEncuesta.App.Proxy.IService1.BeginIniciarSesion(int usuario, string clave, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginIniciarSesion(usuario, clave, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool DigiEncuesta.App.Proxy.IService1.EndIniciarSesion(System.IAsyncResult result) {
            return base.Channel.EndIniciarSesion(result);
        }
        
        private System.IAsyncResult OnBeginIniciarSesion(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int usuario = ((int)(inValues[0]));
            string clave = ((string)(inValues[1]));
            return ((DigiEncuesta.App.Proxy.IService1)(this)).BeginIniciarSesion(usuario, clave, callback, asyncState);
        }
        
        private object[] OnEndIniciarSesion(System.IAsyncResult result) {
            bool retVal = ((DigiEncuesta.App.Proxy.IService1)(this)).EndIniciarSesion(result);
            return new object[] {
                    retVal};
        }
        
        private void OnIniciarSesionCompleted(object state) {
            if ((this.IniciarSesionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.IniciarSesionCompleted(this, new IniciarSesionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void IniciarSesionAsync(int usuario, string clave) {
            this.IniciarSesionAsync(usuario, clave, null);
        }
        
        public void IniciarSesionAsync(int usuario, string clave, object userState) {
            if ((this.onBeginIniciarSesionDelegate == null)) {
                this.onBeginIniciarSesionDelegate = new BeginOperationDelegate(this.OnBeginIniciarSesion);
            }
            if ((this.onEndIniciarSesionDelegate == null)) {
                this.onEndIniciarSesionDelegate = new EndOperationDelegate(this.OnEndIniciarSesion);
            }
            if ((this.onIniciarSesionCompletedDelegate == null)) {
                this.onIniciarSesionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnIniciarSesionCompleted);
            }
            base.InvokeAsync(this.onBeginIniciarSesionDelegate, new object[] {
                        usuario,
                        clave}, this.onEndIniciarSesionDelegate, this.onIniciarSesionCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult DigiEncuesta.App.Proxy.IService1.BeginConsultarUsuario(int usuario, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConsultarUsuario(usuario, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DigiEncuesta.App.Proxy.EntidadEncuestador DigiEncuesta.App.Proxy.IService1.EndConsultarUsuario(System.IAsyncResult result) {
            return base.Channel.EndConsultarUsuario(result);
        }
        
        private System.IAsyncResult OnBeginConsultarUsuario(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int usuario = ((int)(inValues[0]));
            return ((DigiEncuesta.App.Proxy.IService1)(this)).BeginConsultarUsuario(usuario, callback, asyncState);
        }
        
        private object[] OnEndConsultarUsuario(System.IAsyncResult result) {
            DigiEncuesta.App.Proxy.EntidadEncuestador retVal = ((DigiEncuesta.App.Proxy.IService1)(this)).EndConsultarUsuario(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConsultarUsuarioCompleted(object state) {
            if ((this.ConsultarUsuarioCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConsultarUsuarioCompleted(this, new ConsultarUsuarioCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConsultarUsuarioAsync(int usuario) {
            this.ConsultarUsuarioAsync(usuario, null);
        }
        
        public void ConsultarUsuarioAsync(int usuario, object userState) {
            if ((this.onBeginConsultarUsuarioDelegate == null)) {
                this.onBeginConsultarUsuarioDelegate = new BeginOperationDelegate(this.OnBeginConsultarUsuario);
            }
            if ((this.onEndConsultarUsuarioDelegate == null)) {
                this.onEndConsultarUsuarioDelegate = new EndOperationDelegate(this.OnEndConsultarUsuario);
            }
            if ((this.onConsultarUsuarioCompletedDelegate == null)) {
                this.onConsultarUsuarioCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConsultarUsuarioCompleted);
            }
            base.InvokeAsync(this.onBeginConsultarUsuarioDelegate, new object[] {
                        usuario}, this.onEndConsultarUsuarioDelegate, this.onConsultarUsuarioCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override DigiEncuesta.App.Proxy.IService1 CreateChannel() {
            return new Service1ClientChannel(this);
        }
        
        private class Service1ClientChannel : ChannelBase<DigiEncuesta.App.Proxy.IService1>, DigiEncuesta.App.Proxy.IService1 {
            
            public Service1ClientChannel(System.ServiceModel.ClientBase<DigiEncuesta.App.Proxy.IService1> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginIniciarSesion(int usuario, string clave, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = usuario;
                _args[1] = clave;
                System.IAsyncResult _result = base.BeginInvoke("IniciarSesion", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndIniciarSesion(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("IniciarSesion", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginConsultarUsuario(int usuario, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = usuario;
                System.IAsyncResult _result = base.BeginInvoke("ConsultarUsuario", _args, callback, asyncState);
                return _result;
            }
            
            public DigiEncuesta.App.Proxy.EntidadEncuestador EndConsultarUsuario(System.IAsyncResult result) {
                object[] _args = new object[0];
                DigiEncuesta.App.Proxy.EntidadEncuestador _result = ((DigiEncuesta.App.Proxy.EntidadEncuestador)(base.EndInvoke("ConsultarUsuario", _args, result)));
                return _result;
            }
        }
    }
}
