//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("Modelo", "EncuestadorEncuesta", "Encuestador", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DigiEncuesta.Datos.Encuestador), "Encuesta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DigiEncuesta.Datos.Encuesta))]
[assembly: EdmRelationshipAttribute("Modelo", "EncuestaPersona", "Encuesta", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DigiEncuesta.Datos.Encuesta), "Persona", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DigiEncuesta.Datos.Persona))]
[assembly: EdmRelationshipAttribute("Modelo", "EncuestaPregunta", "Encuesta", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DigiEncuesta.Datos.Encuesta), "Pregunta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DigiEncuesta.Datos.Pregunta))]
[assembly: EdmRelationshipAttribute("Modelo", "Tipo_PreguntaPregunta", "Tipo_Pregunta", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DigiEncuesta.Datos.Tipo_Pregunta), "Pregunta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DigiEncuesta.Datos.Pregunta))]
[assembly: EdmRelationshipAttribute("Modelo", "OpcionPregunta", "Opcion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DigiEncuesta.Datos.Opcion), "Pregunta", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DigiEncuesta.Datos.Pregunta))]
[assembly: EdmRelationshipAttribute("Modelo", "RespuestaPregunta", "Respuesta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DigiEncuesta.Datos.Respuesta), "Pregunta", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DigiEncuesta.Datos.Pregunta))]
[assembly: EdmRelationshipAttribute("Modelo", "PersonaRespuesta", "Persona", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DigiEncuesta.Datos.Persona), "Respuesta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DigiEncuesta.Datos.Respuesta))]

#endregion

namespace DigiEncuesta.Datos
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class ModeloContainer : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto ModeloContainer usando la cadena de conexión encontrada en la sección 'ModeloContainer' del archivo de configuración de la aplicación.
        /// </summary>
        public ModeloContainer() : base("name=ModeloContainer", "ModeloContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ModeloContainer.
        /// </summary>
        public ModeloContainer(string connectionString) : base(connectionString, "ModeloContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ModeloContainer.
        /// </summary>
        public ModeloContainer(EntityConnection connection) : base(connection, "ModeloContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Pregunta> Preguntas
        {
            get
            {
                if ((_Preguntas == null))
                {
                    _Preguntas = base.CreateObjectSet<Pregunta>("Preguntas");
                }
                return _Preguntas;
            }
        }
        private ObjectSet<Pregunta> _Preguntas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Respuesta> Respuestas
        {
            get
            {
                if ((_Respuestas == null))
                {
                    _Respuestas = base.CreateObjectSet<Respuesta>("Respuestas");
                }
                return _Respuestas;
            }
        }
        private ObjectSet<Respuesta> _Respuestas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Encuestador> Encuestadores
        {
            get
            {
                if ((_Encuestadores == null))
                {
                    _Encuestadores = base.CreateObjectSet<Encuestador>("Encuestadores");
                }
                return _Encuestadores;
            }
        }
        private ObjectSet<Encuestador> _Encuestadores;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Encuesta> Encuestas
        {
            get
            {
                if ((_Encuestas == null))
                {
                    _Encuestas = base.CreateObjectSet<Encuesta>("Encuestas");
                }
                return _Encuestas;
            }
        }
        private ObjectSet<Encuesta> _Encuestas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Tipo_Pregunta> Tipo_Encuestas
        {
            get
            {
                if ((_Tipo_Encuestas == null))
                {
                    _Tipo_Encuestas = base.CreateObjectSet<Tipo_Pregunta>("Tipo_Encuestas");
                }
                return _Tipo_Encuestas;
            }
        }
        private ObjectSet<Tipo_Pregunta> _Tipo_Encuestas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Opcion> Opciones
        {
            get
            {
                if ((_Opciones == null))
                {
                    _Opciones = base.CreateObjectSet<Opcion>("Opciones");
                }
                return _Opciones;
            }
        }
        private ObjectSet<Opcion> _Opciones;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Persona> Personas
        {
            get
            {
                if ((_Personas == null))
                {
                    _Personas = base.CreateObjectSet<Persona>("Personas");
                }
                return _Personas;
            }
        }
        private ObjectSet<Persona> _Personas;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Preguntas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPreguntas(Pregunta pregunta)
        {
            base.AddObject("Preguntas", pregunta);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Respuestas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToRespuestas(Respuesta respuesta)
        {
            base.AddObject("Respuestas", respuesta);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Encuestadores. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToEncuestadores(Encuestador encuestador)
        {
            base.AddObject("Encuestadores", encuestador);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Encuestas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToEncuestas(Encuesta encuesta)
        {
            base.AddObject("Encuestas", encuesta);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Tipo_Encuestas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTipo_Encuestas(Tipo_Pregunta tipo_Pregunta)
        {
            base.AddObject("Tipo_Encuestas", tipo_Pregunta);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Opciones. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToOpciones(Opcion opcion)
        {
            base.AddObject("Opciones", opcion);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Personas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPersonas(Persona persona)
        {
            base.AddObject("Personas", persona);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Modelo", Name="Encuesta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Encuesta : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Encuesta.
        /// </summary>
        /// <param name="fecha">Valor inicial de la propiedad Fecha.</param>
        /// <param name="muestra">Valor inicial de la propiedad Muestra.</param>
        /// <param name="publico">Valor inicial de la propiedad Publico.</param>
        /// <param name="id_Encuesta">Valor inicial de la propiedad Id_Encuesta.</param>
        /// <param name="nombre_Encuesta">Valor inicial de la propiedad Nombre_Encuesta.</param>
        public static Encuesta CreateEncuesta(global::System.String fecha, global::System.Int32 muestra, global::System.String publico, global::System.Int32 id_Encuesta, global::System.String nombre_Encuesta)
        {
            Encuesta encuesta = new Encuesta();
            encuesta.Fecha = fecha;
            encuesta.Muestra = muestra;
            encuesta.Publico = publico;
            encuesta.Id_Encuesta = id_Encuesta;
            encuesta.Nombre_Encuesta = nombre_Encuesta;
            return encuesta;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private global::System.String _Fecha;
        partial void OnFechaChanging(global::System.String value);
        partial void OnFechaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Muestra
        {
            get
            {
                return _Muestra;
            }
            set
            {
                OnMuestraChanging(value);
                ReportPropertyChanging("Muestra");
                _Muestra = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Muestra");
                OnMuestraChanged();
            }
        }
        private global::System.Int32 _Muestra;
        partial void OnMuestraChanging(global::System.Int32 value);
        partial void OnMuestraChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Publico
        {
            get
            {
                return _Publico;
            }
            set
            {
                OnPublicoChanging(value);
                ReportPropertyChanging("Publico");
                _Publico = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Publico");
                OnPublicoChanged();
            }
        }
        private global::System.String _Publico;
        partial void OnPublicoChanging(global::System.String value);
        partial void OnPublicoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Encuesta
        {
            get
            {
                return _Id_Encuesta;
            }
            set
            {
                if (_Id_Encuesta != value)
                {
                    OnId_EncuestaChanging(value);
                    ReportPropertyChanging("Id_Encuesta");
                    _Id_Encuesta = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id_Encuesta");
                    OnId_EncuestaChanged();
                }
            }
        }
        private global::System.Int32 _Id_Encuesta;
        partial void OnId_EncuestaChanging(global::System.Int32 value);
        partial void OnId_EncuestaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre_Encuesta
        {
            get
            {
                return _Nombre_Encuesta;
            }
            set
            {
                OnNombre_EncuestaChanging(value);
                ReportPropertyChanging("Nombre_Encuesta");
                _Nombre_Encuesta = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre_Encuesta");
                OnNombre_EncuestaChanged();
            }
        }
        private global::System.String _Nombre_Encuesta;
        partial void OnNombre_EncuestaChanging(global::System.String value);
        partial void OnNombre_EncuestaChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Modelo", "EncuestadorEncuesta", "Encuestador")]
        public EntityCollection<Encuestador> Encuestador
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Encuestador>("Modelo.EncuestadorEncuesta", "Encuestador");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Encuestador>("Modelo.EncuestadorEncuesta", "Encuestador", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Modelo", "EncuestaPregunta", "Pregunta")]
        public EntityCollection<Pregunta> Preguntas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Pregunta>("Modelo.EncuestaPregunta", "Pregunta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Pregunta>("Modelo.EncuestaPregunta", "Pregunta", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Modelo", Name="Encuestador")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Encuestador : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Encuestador.
        /// </summary>
        /// <param name="id_Encuestador">Valor inicial de la propiedad Id_Encuestador.</param>
        /// <param name="nombre">Valor inicial de la propiedad Nombre.</param>
        /// <param name="contraseña">Valor inicial de la propiedad Contraseña.</param>
        public static Encuestador CreateEncuestador(global::System.Int32 id_Encuestador, global::System.String nombre, global::System.String contraseña)
        {
            Encuestador encuestador = new Encuestador();
            encuestador.Id_Encuestador = id_Encuestador;
            encuestador.Nombre = nombre;
            encuestador.Contraseña = contraseña;
            return encuestador;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Encuestador
        {
            get
            {
                return _Id_Encuestador;
            }
            set
            {
                if (_Id_Encuestador != value)
                {
                    OnId_EncuestadorChanging(value);
                    ReportPropertyChanging("Id_Encuestador");
                    _Id_Encuestador = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id_Encuestador");
                    OnId_EncuestadorChanged();
                }
            }
        }
        private global::System.Int32 _Id_Encuestador;
        partial void OnId_EncuestadorChanging(global::System.Int32 value);
        partial void OnId_EncuestadorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Contraseña
        {
            get
            {
                return _Contraseña;
            }
            set
            {
                OnContraseñaChanging(value);
                ReportPropertyChanging("Contraseña");
                _Contraseña = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Contraseña");
                OnContraseñaChanged();
            }
        }
        private global::System.String _Contraseña;
        partial void OnContraseñaChanging(global::System.String value);
        partial void OnContraseñaChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Modelo", Name="Opcion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Opcion : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Opcion.
        /// </summary>
        /// <param name="numeral">Valor inicial de la propiedad Numeral.</param>
        /// <param name="texto">Valor inicial de la propiedad Texto.</param>
        /// <param name="id_Opcion">Valor inicial de la propiedad Id_Opcion.</param>
        public static Opcion CreateOpcion(global::System.String numeral, global::System.String texto, global::System.Int32 id_Opcion)
        {
            Opcion opcion = new Opcion();
            opcion.Numeral = numeral;
            opcion.Texto = texto;
            opcion.Id_Opcion = id_Opcion;
            return opcion;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Numeral
        {
            get
            {
                return _Numeral;
            }
            set
            {
                OnNumeralChanging(value);
                ReportPropertyChanging("Numeral");
                _Numeral = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Numeral");
                OnNumeralChanged();
            }
        }
        private global::System.String _Numeral;
        partial void OnNumeralChanging(global::System.String value);
        partial void OnNumeralChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Texto
        {
            get
            {
                return _Texto;
            }
            set
            {
                OnTextoChanging(value);
                ReportPropertyChanging("Texto");
                _Texto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Texto");
                OnTextoChanged();
            }
        }
        private global::System.String _Texto;
        partial void OnTextoChanging(global::System.String value);
        partial void OnTextoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Opcion
        {
            get
            {
                return _Id_Opcion;
            }
            set
            {
                if (_Id_Opcion != value)
                {
                    OnId_OpcionChanging(value);
                    ReportPropertyChanging("Id_Opcion");
                    _Id_Opcion = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id_Opcion");
                    OnId_OpcionChanged();
                }
            }
        }
        private global::System.Int32 _Id_Opcion;
        partial void OnId_OpcionChanging(global::System.Int32 value);
        partial void OnId_OpcionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Modelo", Name="Persona")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Persona : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Persona.
        /// </summary>
        /// <param name="id_Persona">Valor inicial de la propiedad Id_Persona.</param>
        /// <param name="nombre">Valor inicial de la propiedad Nombre.</param>
        /// <param name="barrio">Valor inicial de la propiedad Barrio.</param>
        /// <param name="direccion">Valor inicial de la propiedad Direccion.</param>
        /// <param name="telefono">Valor inicial de la propiedad Telefono.</param>
        /// <param name="edad">Valor inicial de la propiedad Edad.</param>
        public static Persona CreatePersona(global::System.Int32 id_Persona, global::System.String nombre, global::System.String barrio, global::System.String direccion, global::System.String telefono, global::System.Int32 edad)
        {
            Persona persona = new Persona();
            persona.Id_Persona = id_Persona;
            persona.Nombre = nombre;
            persona.Barrio = barrio;
            persona.Direccion = direccion;
            persona.Telefono = telefono;
            persona.Edad = edad;
            return persona;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Persona
        {
            get
            {
                return _Id_Persona;
            }
            set
            {
                if (_Id_Persona != value)
                {
                    OnId_PersonaChanging(value);
                    ReportPropertyChanging("Id_Persona");
                    _Id_Persona = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id_Persona");
                    OnId_PersonaChanged();
                }
            }
        }
        private global::System.Int32 _Id_Persona;
        partial void OnId_PersonaChanging(global::System.Int32 value);
        partial void OnId_PersonaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Barrio
        {
            get
            {
                return _Barrio;
            }
            set
            {
                OnBarrioChanging(value);
                ReportPropertyChanging("Barrio");
                _Barrio = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Barrio");
                OnBarrioChanged();
            }
        }
        private global::System.String _Barrio;
        partial void OnBarrioChanging(global::System.String value);
        partial void OnBarrioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Direccion
        {
            get
            {
                return _Direccion;
            }
            set
            {
                OnDireccionChanging(value);
                ReportPropertyChanging("Direccion");
                _Direccion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Direccion");
                OnDireccionChanged();
            }
        }
        private global::System.String _Direccion;
        partial void OnDireccionChanging(global::System.String value);
        partial void OnDireccionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Telefono
        {
            get
            {
                return _Telefono;
            }
            set
            {
                OnTelefonoChanging(value);
                ReportPropertyChanging("Telefono");
                _Telefono = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Telefono");
                OnTelefonoChanged();
            }
        }
        private global::System.String _Telefono;
        partial void OnTelefonoChanging(global::System.String value);
        partial void OnTelefonoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Edad
        {
            get
            {
                return _Edad;
            }
            set
            {
                OnEdadChanging(value);
                ReportPropertyChanging("Edad");
                _Edad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Edad");
                OnEdadChanged();
            }
        }
        private global::System.Int32 _Edad;
        partial void OnEdadChanging(global::System.Int32 value);
        partial void OnEdadChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Modelo", "EncuestaPersona", "Encuesta")]
        public Encuesta Encuesta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Encuesta>("Modelo.EncuestaPersona", "Encuesta").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Encuesta>("Modelo.EncuestaPersona", "Encuesta").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Encuesta> EncuestaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Encuesta>("Modelo.EncuestaPersona", "Encuesta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Encuesta>("Modelo.EncuestaPersona", "Encuesta", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Modelo", Name="Pregunta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pregunta : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Pregunta.
        /// </summary>
        /// <param name="numeracion">Valor inicial de la propiedad Numeracion.</param>
        /// <param name="texto">Valor inicial de la propiedad Texto.</param>
        /// <param name="id_Pregunta">Valor inicial de la propiedad Id_Pregunta.</param>
        public static Pregunta CreatePregunta(global::System.Int32 numeracion, global::System.String texto, global::System.Int32 id_Pregunta)
        {
            Pregunta pregunta = new Pregunta();
            pregunta.Numeracion = numeracion;
            pregunta.Texto = texto;
            pregunta.Id_Pregunta = id_Pregunta;
            return pregunta;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Numeracion
        {
            get
            {
                return _Numeracion;
            }
            set
            {
                OnNumeracionChanging(value);
                ReportPropertyChanging("Numeracion");
                _Numeracion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Numeracion");
                OnNumeracionChanged();
            }
        }
        private global::System.Int32 _Numeracion;
        partial void OnNumeracionChanging(global::System.Int32 value);
        partial void OnNumeracionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Texto
        {
            get
            {
                return _Texto;
            }
            set
            {
                OnTextoChanging(value);
                ReportPropertyChanging("Texto");
                _Texto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Texto");
                OnTextoChanged();
            }
        }
        private global::System.String _Texto;
        partial void OnTextoChanging(global::System.String value);
        partial void OnTextoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Pregunta
        {
            get
            {
                return _Id_Pregunta;
            }
            set
            {
                if (_Id_Pregunta != value)
                {
                    OnId_PreguntaChanging(value);
                    ReportPropertyChanging("Id_Pregunta");
                    _Id_Pregunta = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id_Pregunta");
                    OnId_PreguntaChanged();
                }
            }
        }
        private global::System.Int32 _Id_Pregunta;
        partial void OnId_PreguntaChanging(global::System.Int32 value);
        partial void OnId_PreguntaChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Modelo", "Tipo_PreguntaPregunta", "Tipo_Pregunta")]
        public Tipo_Pregunta Tipo_Pregunta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tipo_Pregunta>("Modelo.Tipo_PreguntaPregunta", "Tipo_Pregunta").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tipo_Pregunta>("Modelo.Tipo_PreguntaPregunta", "Tipo_Pregunta").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Tipo_Pregunta> Tipo_PreguntaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tipo_Pregunta>("Modelo.Tipo_PreguntaPregunta", "Tipo_Pregunta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Tipo_Pregunta>("Modelo.Tipo_PreguntaPregunta", "Tipo_Pregunta", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Modelo", "OpcionPregunta", "Opcion")]
        public EntityCollection<Opcion> Opciones
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Opcion>("Modelo.OpcionPregunta", "Opcion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Opcion>("Modelo.OpcionPregunta", "Opcion", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Modelo", Name="Respuesta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Respuesta : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Respuesta.
        /// </summary>
        /// <param name="valor">Valor inicial de la propiedad Valor.</param>
        /// <param name="id_Respuesta">Valor inicial de la propiedad Id_Respuesta.</param>
        public static Respuesta CreateRespuesta(global::System.String valor, global::System.Int32 id_Respuesta)
        {
            Respuesta respuesta = new Respuesta();
            respuesta.Valor = valor;
            respuesta.Id_Respuesta = id_Respuesta;
            return respuesta;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Valor
        {
            get
            {
                return _Valor;
            }
            set
            {
                OnValorChanging(value);
                ReportPropertyChanging("Valor");
                _Valor = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Valor");
                OnValorChanged();
            }
        }
        private global::System.String _Valor;
        partial void OnValorChanging(global::System.String value);
        partial void OnValorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Respuesta
        {
            get
            {
                return _Id_Respuesta;
            }
            set
            {
                if (_Id_Respuesta != value)
                {
                    OnId_RespuestaChanging(value);
                    ReportPropertyChanging("Id_Respuesta");
                    _Id_Respuesta = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id_Respuesta");
                    OnId_RespuestaChanged();
                }
            }
        }
        private global::System.Int32 _Id_Respuesta;
        partial void OnId_RespuestaChanging(global::System.Int32 value);
        partial void OnId_RespuestaChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Modelo", "RespuestaPregunta", "Pregunta")]
        public Pregunta Pregunta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pregunta>("Modelo.RespuestaPregunta", "Pregunta").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pregunta>("Modelo.RespuestaPregunta", "Pregunta").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Pregunta> PreguntaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pregunta>("Modelo.RespuestaPregunta", "Pregunta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Pregunta>("Modelo.RespuestaPregunta", "Pregunta", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Modelo", "PersonaRespuesta", "Persona")]
        public Persona Persona
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Persona>("Modelo.PersonaRespuesta", "Persona").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Persona>("Modelo.PersonaRespuesta", "Persona").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Persona> PersonaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Persona>("Modelo.PersonaRespuesta", "Persona");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Persona>("Modelo.PersonaRespuesta", "Persona", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Modelo", Name="Tipo_Pregunta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tipo_Pregunta : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Tipo_Pregunta.
        /// </summary>
        /// <param name="id_TipoPregunta">Valor inicial de la propiedad Id_TipoPregunta.</param>
        /// <param name="descripcion">Valor inicial de la propiedad Descripcion.</param>
        public static Tipo_Pregunta CreateTipo_Pregunta(global::System.Int32 id_TipoPregunta, global::System.String descripcion)
        {
            Tipo_Pregunta tipo_Pregunta = new Tipo_Pregunta();
            tipo_Pregunta.Id_TipoPregunta = id_TipoPregunta;
            tipo_Pregunta.Descripcion = descripcion;
            return tipo_Pregunta;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_TipoPregunta
        {
            get
            {
                return _Id_TipoPregunta;
            }
            set
            {
                if (_Id_TipoPregunta != value)
                {
                    OnId_TipoPreguntaChanging(value);
                    ReportPropertyChanging("Id_TipoPregunta");
                    _Id_TipoPregunta = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id_TipoPregunta");
                    OnId_TipoPreguntaChanged();
                }
            }
        }
        private global::System.Int32 _Id_TipoPregunta;
        partial void OnId_TipoPreguntaChanging(global::System.Int32 value);
        partial void OnId_TipoPreguntaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();

        #endregion
    
    }

    #endregion
    
}
